# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_stages: [pre-commit]
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v10.0.2" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: ["javascript", "ts", "json"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-tabs
      - id: remove-crlf
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.9
    hooks:
      - id: search-and-replace
        stages: [commit-msg, pre-commit]
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        exclude: ^.*-hook/src/.*/models.py$
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        exclude: ^.*\.aws-sam.*$
  - repo: https://github.com/pycqa/isort
    rev: 8.0.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^.*-hook/src/.*/models.py$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ['--verbose']
        verbose: true  # print warnings
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v1.45.0
    hooks:
      - id: cfn-python-lint
        files: ^(?!\..*).*/template\.(json|yml|yaml)$
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.506'
    hooks:
      - id: checkov
        verbose: true
        args: [--soft-fail]
